highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-feed
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
permalink: /:year/:month/:day/:title:output_ext
